### PR TITLE
Add new mips xtoolchain jobs

### PR DESCRIPTION
**Pull request by kevans91**
This is an alternative to PR #36, as discussed with lwhsu. Add new xtoolchain jobs for mips/mips64 using mips-gcc/mips64-gcc respectively, and change the warn scanner to "gcc" in that new job to address @bsdjhb's commentary. The new job is suitable for at least head and stable/12 and some do use mips-xtoolchain-gcc (e.g. freebsd-wifi-build users), so we might as well enable it on stable/12 as well to be sure.

### CODE REVIEW

**Comment by kevans91** [comment]
> Soon we will want to use 'mips-gcc6' as the package instead of mips-xtoolchain-gcc.

Will there be a transition period where they co-exist, or will it be an immediate rm+add?

**Comment by bsdjhb** [comment]
On 12/16/19 1:55 PM, Kyle Evans wrote:
>> Soon we will want to use 'mips-gcc6' as the package instead of mips-xtoolchain-gcc.
> 
> Will there be a transition period where they co-exist, or will it be an immediate rm+add?

The new ports already exist.  I plan to leave the old ones around for a long-ish
time.

-- 
John Baldwin

**Comment by lwhsu** [comment]
How about mipsn32?

**Comment by bsdjhb** [comment]
Actually, I was doing some further fixes to switch to the freebsd-gcc6 packages, but it looks like this won't work on stable-12 since there aren't any stable-12 jobs in the jobs/ subdirectory?

I think what we really want is to have 'gcc6' jobs that use freebsd-gcc6 (and eventually 'gcc9' jobs once head is ready) that just build world + kernel like the amd64-gcc job (we should probably make a new script that just does world-kernel, or rename the existing world-kernel script to 'world-kernel-release' or some such and make world-kernel just do what the amd64-gcc job does.

Then I think we want to enable 'gcc6' jobs when gcc6 is not the default (e.g. stable/12), but I think we want the default head job to use external GCC as my original change did, since GCC 4 is going to be removed soon from HEAD.

**Comment by kevans91** [comment]
> Then I think we want to enable 'gcc6' jobs when gcc6 is not the default (e.g. stable/12), but I think we want the default head job to use external GCC as my original change did, since GCC 4 is going to be removed soon from HEAD.

lwhsu and I discussed this one, but I'm starting to think it was IRC -- he has a strong preference to keep the default job using in-tree as long as in-tree works.

**Comment by bsdjhb** [comment]
Well, the goal is to kill the in-tree GCC on 12/31, and I'd like to get the new version tested in CI before that date if possible.

**Comment by bsdjhb** [comment]
Hmm, I can't find the xtoolchain jobs on ci.freebsd.org either now, perhaps the job names in the yaml file don't match and that is why?

**Comment by lwhsu** [comment]
Oh there are some more issues in the yaml and I was thinking to merge it first and fix them. I’ll work on these very soon.

**Comment by lwhsu** [comment]
Well, my preference is not that “strong” but I feel it is nice if the job name can reflect the actual build method.  One day we may use the -build one when LLVM/Clang supports. I think having xtoolchain, gcc6, gcc9 jobs is great and I will work on adding them soon.

**Comment by bsdjhb** [comment]
So I have a patchset to rename most of the xtoolchain ones to gcc6, but I'm not sure how to update the yaml file.  If you can update the yaml file to make the current ones work, I can finish my gcc6 change.  We can add gcc9 jobs once gcc9 builds at least some platforms cleanly.  (I think we are close on amd64 at least.)

**Pull request merged**
