### PR TITLE
Add armv6 testvm/test

### PR DESCRIPTION
**Pull request by trasz**
This adds two new jobs.  The reason (apart from not having tests for armv6 atm) is that this way I can start from scratch without the risk of breaking existing jobs.

Could you also spin up those two jobs on CI? Note that it will be almost certainly red for the next couple of days.  Thanks!

### CODE REVIEW

**Comment by lwhsu** [comment]
It generally looks good to me. Can you give me a rough idea about how long might it take for a run? I need to set timeout limit for this job.

**Comment by trasz** [comment]
I think one hour should be fine for now.

**Comment by lwhsu** [comment]
Oh I forgot about we need a `pkg-list` for installing packages in the jail. Do we want `qemu-devel`?

**Comment by trasz** [comment]
Ah, so _that's_ what it is for.  Done :-)

**Comment by lwhsu** [comment]
I guess we don't need other packages than qemu?

**Comment by trasz** [comment]
I've removed the one we certainly don't need; the others...  Oh well, you're probably right.

**Comment by lwhsu** [comment]
I'll take care of the job configurations later.

**Pull request merged**
