### PR TITLE
Reenable the fusefs tests

### PR DESCRIPTION
**Pull request by asomers**
As of r360567 they should be able to pass on head

### CODE REVIEW

**Comment by asomers** [comment]
Note that the fix has not yet been MFCed.

**Comment by lwhsu** [comment]
> Note that the fix has not yet been MFCed.

Then I think merging this will affect -stable's test jobs?

**Comment by asomers** [comment]
Yes, unless there's some way to apply that shell script to head but not stable builds.  I didn't see any.  Or, we can just let this PR set here until I MFC, which should be in 13 days.

**Comment by lwhsu** [comment]
> Yes, unless there's some way to apply that shell script to head but not stable builds. I didn't see any. Or, we can just let this PR set here until I MFC, which should be in 13 days.

Thanks for confirming this. I will check if I can have a way to solve this in 13 days, or just merging this after it gets MFC'd.

**Comment by asomers** [comment]
Ok @lwhsu this should be good to merge now.  I just MFCed the fix to stable/12, and it doesn't apply to stable/11.

**Pull request merged**
