### PR TITLE
Add custom src.conf files to build alternate kernels

### PR DESCRIPTION
**Pull request by chmeeedalf**
For powerpcspe we need to instead build MPC85XXSPE, and the others need
to build the Book-E kernels in addition to GENERIC*.

### CODE REVIEW

**Comment by chmeeedalf** [comment]
I hope the paths are correct.  I didn't test the changes.

**Comment by lwhsu** [comment]
Do you think these alternate kernels should be part of the "default" build, or having them as downstream builds like "LINT"?

**Comment by chmeeedalf** [comment]
What do you mean by downstream builds? I know at least powerpcspe needs its
kernel correct. The others should build the book-e kernels just to be safe
(most changes that might impact should be caught by the default kernels),
but I also will want these kernels when disk images are built.

- Justin

**Comment by lwhsu** [comment]
Downstream job means a job that will be triggered after a job has finished.  For example, `FreeBSD-head-amd64-build` job, which builds GENERIC kernel, triggers `FreeBSD-head-amd64-LINT` job, which builds the LINT kernel only.

For powerpc64 builds, I propose we have `GENERIC64` as default build, and add one more `QORIQ64` downstream job, which builds QORIQ64 then uploads `kernel-QORIQ64.txz` to artifact server.  How do you think?  We can of course have another job test that kernel afterward.

**Pull request merged**
